#ifndef RUNA_LIMITS_H
#define RUNA_LIMITS_H

#define RUNA_PROTOCOL_VERSION 1u
#define RUNA_IR_VERSION 1u
#define RUNA_REGISTER_COUNT 8u
#define RUNA_MAX_JOB_BYTES 2048u
#define RUNA_MAX_INSTRUCTIONS 256u
#define RUNA_MAX_STEPS 10000u
#define RUNA_MAX_RUNTIME_US 5000000u
#define RUNA_MAX_RESULT_BYTES 32u
#define RUNA_MAX_EMITS 128u
#define RUNA_MAX_EMIT_BYTES 512u
#define RUNA_MAX_SINGLE_DELAY_MS 1000u
#define RUNA_MAX_RESOURCES 64u
#define RUNA_MAX_EVENT_BYTES 64u
#define RUNA_HEADER_SIZE 40u

#endif
