#ifndef JOB_ERROR_H
#define JOB_ERROR_H

typedef enum job_error {
    JOB_OK = 0,
    JOB_ERR_INVALID_FORMAT = 1,
    JOB_ERR_BAD_MAGIC = 2,
    JOB_ERR_UNSUPPORTED_PROTOCOL = 3,
    JOB_ERR_UNSUPPORTED_IR_VERSION = 4,
    JOB_ERR_JOB_TOO_LARGE = 5,
    JOB_ERR_INVALID_OPCODE = 6,
    JOB_ERR_INVALID_OPERAND = 7,
    JOB_ERR_INVALID_REGISTER = 8,
    JOB_ERR_INVALID_JUMP = 9,
    JOB_ERR_INVALID_RESOURCE = 10,
    JOB_ERR_RESOURCE_TYPE = 11,
    JOB_ERR_ACCESS_DENIED = 12,
    JOB_ERR_OUT_OF_RANGE = 13,
    JOB_ERR_STEP_LIMIT = 14,
    JOB_ERR_RUNTIME_LIMIT = 15,
    JOB_ERR_RESULT_LIMIT = 16,
    JOB_ERR_EMIT_LIMIT = 17,
    JOB_ERR_GPIO = 18,
    JOB_ERR_ADC = 19,
    JOB_ERR_PWM = 20,
    JOB_ERR_IO_TIMEOUT = 21,
    JOB_ERR_CANCELLED = 22,
    JOB_ERR_INTERNAL = 23
} job_error_t;

#endif

